export type Place={id:string;name:string;category:string;type:string;area:string;price:number;rating:number;count:number;returnRate:number;image:string;description:string;tags:string[];lat:number;lng:number;address:string;hours:string;services:string[];phone?:string;website?:string;instagram?:string;owner?:string;demo:boolean};
export const places:Place[]=[
{id:'sahil',name:'SAHiL',category:'Restaurants',type:'Seafood · Azerbaijani',area:'Sahil',price:3,rating:9.1,count:438,returnRate:92,image:'/images/restaurant.jpg',description:'A relaxed table by the Caspian. Contemporary Azerbaijani flavours, warm interiors and long evenings with friends.',tags:['Seafood','Outdoor seating','Family friendly','Parking'],lat:40.369,lng:49.846,address:'Baku Boulevard, Baku',hours:'12:00–00:00',services:['Menu details awaiting verification'],demo:true},
{id:'fuego',name:'Fuego',category:'Restaurants',type:'Steakhouse',area:'Nizami',price:3,rating:9.3,count:312,returnRate:95,image:'/images/restaurant.jpg',description:'An intimate steakhouse setting in the heart of the city. A place for slow dinners and good conversation.',tags:['Steak','Romantic','Alcohol','Parking'],lat:40.373,lng:49.838,address:'Nizami area, Baku',hours:'12:00–00:00',services:['Menu details awaiting verification'],demo:true},
{id:'lea',name:'Léa Beauty Lounge',category:'Beauty & Spa',type:'Hair · Nails · Spa',area:'Port Baku',price:2,rating:9.4,count:310,returnRate:96,image:'/images/spa.jpg',description:'A calm space for a little time to yourself. Hair, nails and everyday beauty rituals in a light-filled salon.',tags:['Hair','Nails','Facial','Massage','Laser','Makeup','Spa'],lat:40.377,lng:49.863,address:'Port Baku area, Baku',hours:'10:00–20:00',services:['Haircut — 35–60 AZN','Manicure — 25 AZN','Massage — 70 AZN','Laser — from 40 AZN'],demo:true},
{id:'leyla',name:'Dr. Leyla Mammadova',category:'Doctors',type:'Dermatologist',area:'Nasimi',price:2,rating:9.6,count:124,returnRate:94,image:'',description:'Demonstration professional profile. Qualifications, clinic affiliation and contact information must be verified before public launch.',tags:['Dermatologist','AZ','RU','EN'],lat:40.387,lng:49.842,address:'Nasimi, Baku',hours:'09:00–18:00',services:['Consultation — 80 AZN (sample)','Languages — AZ, RU, EN','Clinic — Baku Medical Center (sample)'],demo:true},
{id:'rooftop',name:'Caspian Rooftop',category:'Nightlife',type:'Rooftop · Lounge',area:'Sahil',price:3,rating:9.0,count:187,returnRate:91,image:'/images/baku.jpg',description:'City lights, an open-air terrace and late-night conversations overlooking the Caspian.',tags:['Live music','Live DJ','Outdoor seating','Alcohol'],lat:40.371,lng:49.85,address:'Sahil area, Baku',hours:'18:00–02:00',services:['Music — Lounge / House','Dress code — Smart casual','Entry — Contact venue','Reservations recommended','Age — 18+'],demo:true},
{id:'cafe',name:'Sunday Coffee',category:'Cafés',type:'Coffee · Breakfast',area:'Icherisheher',price:1,rating:8.9,count:96,returnRate:93,image:'/images/restaurant.jpg',description:'Your unhurried morning in the old city. Coffee, breakfast and a quiet corner.',tags:['Breakfast','Coffee','Family friendly','Outdoor seating'],lat:40.365,lng:49.835,address:'Icherisheher, Baku',hours:'08:00–22:00',services:['Menu details awaiting verification'],demo:true},
{id:'clinic',name:'Baku Medical Center',category:'Clinics',type:'Multispecialty clinic',area:'Nasimi',price:2,rating:9.0,count:83,returnRate:90,image:'',description:'Demonstration clinic listing, with reviews focused on reception, cleanliness and the clinic experience.',tags:['Dentist','Cardiologist','Pediatrician','ENT'],lat:40.388,lng:49.842,address:'Nasimi, Baku',hours:'09:00–18:00',services:['Dermatology','Cardiology','Pediatrics'],demo:true}
];
export const scoreTypes=(p:Place)=>p.category==='Doctors'?['Communication','Waiting time','Clarity of explanation','Clinic experience','Overall experience']:p.category==='Clinics'?['Reception','Cleanliness','Waiting time','Organization','Service']:p.category==='Beauty & Spa'?['Service','Cleanliness','Result','Atmosphere','Value']:['Food','Service','Atmosphere','Value'];
